# Copyright NTESS. See COPYRIGHT file for details.
#
# SPDX-License-Identifier: MIT

import os
import subprocess
from typing import TextIO


def version_components_from_git(full: bool = False) -> tuple[int, int, int, str]:
    try:
        save_cwd = os.getcwd()
        os.chdir(os.path.join(os.path.dirname(__file__), "../../.."))
        args = ["git", "log", "-1", "--pretty=format:%ad %h", "--date=short"]
        proc = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        proc.wait()
        out, _ = [_.decode("utf-8") for _ in proc.communicate()]
        date, local, *_ = out.split()
        major, minor, micro = [int(_) for _ in date.split("-")]
        if full:
            proc = subprocess.Popen(["git", "diff", "--quiet"])
            proc.wait()
            if proc.returncode:
                local += "-dirty"
        return major - 2000, minor, micro, local
    finally:
        os.chdir(save_cwd)


def write_version_file(file: TextIO, major: int, minor: int, micro: int, local: str) -> None:
    file.write(
        f"""# Version file automatically generated by hpc_connect

__static_version_tuple__: tuple[int, int, int, str] = ({major}, {minor}, {micro}, {local!r})
__static_version__: str = "{major}.{minor}.{micro}+{local}"

def __getattr__(name):
    import os

    from hpc_connect.util.dynamic_version import version_components_from_git

    if name not in ("version", "__version__", "version_info", "__version_info__"):
        raise AttributeError(name)
    f = os.path.join(os.path.dirname(__file__), "../../.git")
    if os.path.exists(f):
        major, minor, micro, local = version_components_from_git(full=True)
        if name in ("version", "__version__"):
            return f"{{major}}.{{minor}}.{{micro}}+{{local}}"
        else:
            return (major, minor, micro, local)
    elif name in ("version", "__version__"):
        return __static_version__
    else:
        return __static_version_tuple__
"""
    )


def __getattr__(name):
    if name == "__generate_dynamic_version__":
        major, minor, micro, local = version_components_from_git()
        with open(os.path.join(os.path.dirname(__file__), "../version.py"), "w") as fh:
            write_version_file(fh, major, minor, micro, local)
        if "NO_LOCAL_VERSION" in os.environ:
            return f"{major}.{minor}.{micro}"
        return f"{major}.{minor}.{micro}+{local}"
    raise AttributeError(name)
