ARG BASE_IMAGE=pbspro/pbspro:latest
FROM ${BASE_IMAGE}

LABEL org.opencontainers.image.title="hpc-connect-pbs"
LABEL org.opencontainers.image.description="hpc-connect CI base image for PBS tests"
LABEL org.opencontainers.image.source="https://github.com/sandialabs/hpc-connect"
